### PR TITLE
Advanced file sharing

### PR DESCRIPTION
**Pull request by kevinmershon**
File sharing still isn't working. Try the following user accounts at http://hydra-staging.elasticbeanstalk.com

- admin@example.com (password admin@example.com)
- manager@example.com (password manager@example.com)

The admin user can see everything, from what I can tell. The manager user gets redirected back to the login any time they try to interact with their own file shared with admin@example.com, or the file shared with them by admin@example.com

### CODE REVIEW

**Comment by cpascua** [comment]
@kevinmershon I've added 3 basic users to make sure that view "shared with others" and "shared with me" files were view correctly with basic users.  I also discovered why manager wasn't able to open attachments.  Viewing attachments requires the "View Attachment" access level which `manager@example.com` didn't have.  I'll have to look through the access levels and verify which ones access levels should be granted to admins, managers and basic users.  I'm assuming admins should have all access levels by default.  I'll need to clarify with you what managers and basic users can do.  Also there seems to be other access levels that are not used by hydra-core, as far the attachments viewer goes, like `View Clients`, `View Same Client data` and `View Same Client Location Data`.  I believe these are for the data-gatherer, but I can't say for certain.  Otherwise, the sharing attachment features should be behaving correctly now.  The reset.sh script has been updated to create the 3 basic users and assign the proper access levels for managers and basic users so they can at least view owned and shared with files and submit files.

**Comment by kevinmershon** [comment]
Well, the idea is to have privileges be a matrix of possibilities, not explicit 'Admin', 'Manager', and 'Basic' roles. For instance, I could have a subcontractor who I want to be able to see a list of all my clients and create data for any of them, but only be able to view data and attachments they submitted themselves. Or, I might have a manager user in my company who I want to be able to create and edit privileges on users, but they don't need to see any data or files except for one particular client which I want them to have full privileges on.

The most frustrating thing I kept running into with the staging system is that if the right privileges aren't set, it should never just kick me back to the login screen. That's why we have error code `401` for "unauthorized" (you are not logged in) vs. `403` for "access denied" (you're logged in but you don't have access to that). It seems instead of using `403` anywhere, we're using `409` (which means "conflict": a backend error of some kind that isn't `404` or `500`).

**Comment by cpascua** [comment]
@kevinmershon I've made the changes to the web-app so that you aren't immediately logged off whenever you try to view attachments without the correct access level.  Instead you receive a notification of the access level required for the action.  One issue with this is that when clicking to view an attachment, the web app begins to build out the attachment view page before the back-end can return the 403 status.  After the 403 response is retrieve by the web app, the user is immediately redirected back to the the explorer view.  Fortunately the list page, limit and offset are cached, so you are returned to explorer view you were at last.  We should probably handle this more elegantly by retrieving access levels on login and then adding the restrictions on what is clickable based on the access level or something like that. We still need to apply this to all the other actions in the web-app, but I think we should create a new issue for figuring out what we want to do and implementing it everywhere.

As for the default access levels for each role, it looks like the the admin, manager and basic are just labels, since you could possibly give a basic user all access levels or give an admin no access levels.       Or is it that only admins can modify, access levels?  We don't have an user management view for that anyway but we should probably build one.

**Comment by cpascua** [comment]
@kevinmershon also, as far as the sharing feature is concerned, there doesn't seem to be any other issues with viewing what is shared with a you.  The issue you mentioned for manager were due to missing the "View Attachments" access level.  I can also confirm that I do have restclient tests here, https://github.com/mershon-enterprises/hydra-core/blob/feature-file-sharing/rest-client/test/restclient_test.js#L2503-L3430, to verify sharing is working correctly.  If there isn't anything I've missed, I'd like to merge this branch into development.

**Comment by kevinmershon** [comment]
Ok, I'll do a new staging deploy Monday and test it all out. If it looks good, then we're ready to merge to development and unblocked. I'm very happy to hear this.

**Comment by kevinmershon** [comment]
OK, I'm starting the review of this branch. First thing I've noticed is vendor scripts is more than 350k, which is pretty atrocious for load time from a tiny web server. Why are we not using CDNs for all of our bower dependencies?

**Comment by kevinmershon** [comment]
Looks good!

**Pull request merged**
