### PR TITLE
Feature fix liquibase auto migration

### PR DESCRIPTION
**Pull request by cpascua**
@kevinmershon This fix is built off an earlier pull request here, https://github.com/mershon-enterprises/hydra-core/pull/11, which has a pending code review.  Changes here are meant to fix auto migration with liquibase.  This time I've double check that all tests are passing after the app automatically builds the database using liquibase.  I've also started using environment variables to specify xml file paths instead of using context like we've done in other projects.  You'll need to update the profiles.clj to include the key `:changelog-path`.  Also, after running the app on your local machine, you should be able also grab the data from the databasechangelog table but be sure to remove the the rows with author, "Development".

### CODE REVIEW

**Comment by kevinmershon** [comment]
@cpascua I have to ask, why did you add the requirement of changelog paths instead of using context? Context is the appropriate way in a web archive to reference relative paths to an application container.

**Comment by cpascua** [comment]
@kevinmershon when using context, I would need to have changelogs for every environment, dev/test/staging/prod/etc all in the same xml file.  I would have to label each changelogs with a context specifying each  environment it would be used for.
Production changelogs would be used for every environment so I'd specify each production changelog with
``` context="prod or dev or staging or test" ```
For only development changelogs that would include mock data and local machine database configuration(like postgres extensions which aren't required in production)
``` context="dev" ```
Since you mentioned before the desire to separate production, development and testing changelogs into different files I implemented the use of the the environment variable `:changelog-path` to specify xml files for each directly.  This negated to requirement `context` since every changelog in the development xml file would only be for development.  Also, since its possible to import xml changelogs into other xml changelogs, when creating the development changelog, I can import production xml changelogs first before adding anything else.  

Most of this you mostly likely already know but I had to go through that for myself as well to validate my reasons.  So in short I'm trading off 
- the use of specifying changelog with context which will require _all_ changelogs for each environment to be included in a single file/souce 

_for_ 
- specifying changlog path which allows me to separate changelogs into different files for each environment negating the need to use and manage context.

**Comment by cpascua** [comment]
@kevinmershon I've removed implementation of using changelog paths and are now using liqubase context to specify environment builds as you have a recommended.  This is ready to be merged in.  Apologizes for taking so long to get this completed.  After coming back from my time off, it has taken me awhile to remember what I was doing, especially, when jumping between other projects.

**Comment by cpascua** [comment]
@kevinmershon I've updated the logic in the shared init for conditional database migrations for prod and dev environments [here](https://github.com/mershon-enterprises/hydra-core/blob/feature-fix-liquibase-auto-migration/web-service/src/web_service/shared_init.clj#L12-L14.).  I've added another profile property call `profile` which is used to identify the profile is `prod`, `dev`, or `test`, because this seems to be the easiest way to get the current environment’s name.  I should also not that `liquibase dropAll` is called in the `test` and `dev` environments and only in those environments.  I made additional changes to the liquibase changelog and contexts.  This should fix the instability problems with development involving web-service tests and restclient tests but not the sharing issue which wil be handled here Pull #11.  Just need you to review and confirm stability for merger back into development.

**Pull request closed without merging**
